# Server Port
server.port=${PORT:8080}

# MongoDB configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/todo}

# Disable Spring Boot banners for cleaner startup logs
spring.main.banner-mode=off

# Show SQL/Queries if needed (optional)
# logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
